version: "3.5"
services:
  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: fiware-orion
    expose:
      - "1026"
    ports:
      - "1026:1026"
    depends_on:
      - mongo-db
    command: -dbhost mongo-db -logLevel DEBUG

  mongo-db:
    image: mongo:5.0
    hostname: mongo-db
    container_name: db-mongo
    ports:
      - "27017:27017" 
    networks:
      - default
    command: --nojournal
    volumes:
      - mongo-db:/data

  nodejs:
    image: node:latest
    hostname: nodejs
    container_name: nodejs-server-for-fiware
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./server:/app
    command: npm start

volumes:
  mongo-db: ~
